#!/bin/sh
tmux new-session -s minide   -n code -d

tmux new-window  -t minide:2 -n run
tmux new-window  -t minide:3 -n gdb
tmux new-window  -t minide:4 -n files
tmux new-window  -t minide:5 -n git
tmux new-window  -t minide:6 -n kanban

tmux send-keys -t 'files' 'man tmux' Enter
tmux send-keys -t 'git' 'git log' Enter
tmux send-keys -t 'kanban' 'taskell' Enter

tmux select-window -t minide:1
tmux -2 attach-session -t minide
